baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "poboo.github.io" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text vagrant, wanderer, tramp, satyr
title: The Twelve Dancing Princesses :)
header: A vagabond... 

# for welcome page
# to replace image go to index.html
email:
  address: "poboerz@163.com"
  text: "poboerz#163.com"


gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
